(module
  (func $r3_main (export "_start") (export "main")
    call $app_1)
  (func $app_1 (export "app_1")
    call $app_2)
  (func $app_2 (export "app_2")
    call $app_3)
  (func $app_3 (export "app_3")
    call $app_4)
  (func $app_4 (export "app_4")
    call $app_5)
  (func $app_5 (export "app_5")
    i32.const 55 drop))
