(module
(func $r3_main (export "_start") (export "main")
    call $app_0)
  (func $app_0 (export "app_0")
    call $app_1)
  (func $app_1 (export "app_1")
    call $app_2)
  (func $app_2 (export "app_2")
    call $app_3)
  (func $app_3 (export "app_3")
    call $app_4)
  (func $app_4 (export "app_4")
    call $app_5)
  (func $app_5 (export "app_5")
    call $app_6)
  (func $app_6 (export "app_6")
    call $app_7)
  (func $app_7 (export "app_7")
    call $app_8)
  (func $app_8 (export "app_8")
    call $app_9)
  (func $app_9 (export "app_9")
    call $app_10)
  (func $app_10 (export "app_10")
    i32.const 4420 drop)
)