(module
  (memory (export "memory") 1)
  (table 6 funcref)
  (type $v (func))
  (type $i (func (param i32)))
  (type $ii (func (param i32 i32)))
  (elem (i32.const 0) $r3_v $r3_i $r3_ii $r3_v $r3_i $r3_ii)
  (func $r3_main (export "_start")(export "main") call $driver)
  (func $driver (export "driver")
    i32.const 0 call_indirect (type $v)
    i32.const 1 i32.const 1 call_indirect (type $i)
    i32.const 7 i32.const 8 i32.const 2 call_indirect (type $ii))
  (func $r3_v (type $v) nop)
  (func $r3_i (type $i) (param i32) nop)
  (func $r3_ii (type $ii) (param i32 i32) nop))
